apiVersion: v2
name: warden
description: Uptime monitoring with adaptive latency alerts and status pages
type: application
version: 0.3.2
appVersion: "0.8.0"
icon: https://raw.githubusercontent.com/projecthelena/warden/main/assets/favicon.svg
home: https://github.com/projecthelena/warden
sources:
  - https://github.com/projecthelena/warden
  - https://github.com/projecthelena/helm-charts
keywords:
  - monitoring
  - uptime
  - status-page
  - kubernetes
maintainers:
  - name: Project Helena
    email: jesus@projecthelena.com
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/projecthelena/warden/issues
    - name: Documentation
      url: https://github.com/projecthelena/warden/tree/main/docs
